config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:index] do
    member do
      match 'scorecard' => "users#scorecard", via: [:get, :post]
    end
  end

  resources :scores

  root to: "users#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/performance.rb
class Performance < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :scores

  scope :scores_excluding_user, -> (user) { joins(:scores).where('scores.user_id != ?', user.id) }

  def totals
    {
      song: self.scores.sum(:song),
      backdrop: self.scores.sum(:backdrop),
      outfit: self.scores.sum(:outfit)
    }
  end

  def song_score
    self.scores.sum(:song)
  end

  def backdrop_score
    self.scores.sum(:backdrop)
  end

  def outfit_score
    self.scores.sum(:outfit)
  end

  def overall_score
     self.scores.sum(:song) + self.scores.sum(:backdrop) + self.scores.sum(:outfit)
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :user
  belongs_to :performance

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :performances
  has_many :scores

  def scores_excluding_me
    scores.joins(:performance).where('performances.user_id != ?', self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def index

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def scorecard

    @user = User.friendly.find(params[:id])

    if params[:scorecard].present?

      performances = params[:scorecard].permit!

      performances.each do |performance|
        Score.find(performance[0]).update_attributes({
          song: performance[1]["song"],
          outfit: performance[1]["outfit"],
          backdrop: performance[1]["backdrop"]
        })
      end

      @notice = "Scorecard saved"

    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.haml
%header#site-header.px-5.bg-blue.text-center.py-5.mb-4
  .pt-2
    =link_to root_path do
      =image_tag("crisovision.png", :alt => "Crisovision")
  .row.mt-4.pt-2
    .col-md-6.text-md-right
      %p.pb-0.mb-0.pr-3
        =link_to "https://us02web.zoom.us/j/75149271147", target: "_blank" do
          %em.fa.fa-theater-masks.mr-2
          Perform on Zoom
    .col-md-6.text-md-left
      %p.pb-0.mb-0
        =link_to "https://www.watch2gether.com/rooms/crisovision-vejzzgfaptkvqfctt5", target: "_blank" do
          %em.fa.fa-video.mr-2
          Sync music on Watch2Gether

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crisovision</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "application/header" %>

    <section id="main-content" class="px-5 mb-4 pb-4 pt-4">
      <%- if @notice.present? %>
        <div class="notice">
          <%= @notice %>
        </div>
      <% end %>
      <%= yield %>
    </section>

    <footer>
      <!--<p class="small"><%= link_to "Scoreboard", scores_path %>-->
    </footer>

  </body>
</html>

app/views/scores/index.haml
.px-5.mb-5.pb-4.pt-4
  .text-center
    %h2.mb-4 Overall winner
    -@winner = Performance.all.joins(:scores).uniq.sort_by{ |p| p.overall_score }.reverse.first
  .text-center
    .score_badge.mb-3
      ="#{@winner.overall_score}"
    %h4=@winner.title
    %p=@winner.user.name

.row.text-center.mb-5
  .col-md-4
    %h2.mb-4 Performance – Top 3
    .mt-3
      -Performance.all.joins(:scores).uniq.sort_by{ |p| p.song_score }.reverse.first(3).each_with_index do |performance, i|
        .mb-4.pb-1
          .score_badge.mb-3
            =i+1
          %h4=performance.title
          %p=performance.user.name
  .col-md-4
    %h2.mb-4 Outfit – Top 3
    .mt-3
      -Performance.all.joins(:scores).uniq.sort_by{ |p| p.outfit_score }.reverse.first(3).each_with_index do |performance, i|
        .mb-4.pb-1
          .score_badge.mb-3
            =i+1
          %h4=performance.title
          %p=performance.user.name
  .col-md-4
    %h2.mb-4 Stage – Top 3
    .mt-3
      -Performance.all.joins(:scores).uniq.sort_by{ |p| p.backdrop_score }.reverse.first(3).each_with_index do |performance, i|
        .mb-4.pb-1
          .score_badge.mb-3
            =i+1
          %h4=performance.title
          %p=performance.user.name

.row
  .col-md-3
  .col-md-6
    .pb-3.pt-3.text-center
      %h1.mb-5 Scoreboard
      -Performance.all.joins(:scores).uniq.sort_by{ |p| p.overall_score }.reverse.each_with_index do |performance, i|
        .row.mb-4
          .col-2
            .score_badge
              =i+1
          .col-10.score-block
            %h4=performance.title
            %p=performance.user.name
            %ul.score_list
              %li
                %span Performance
                =performance.totals[:song]
              %li
                %span Outfit
                =performance.totals[:outfit]
              %li
                %span Stage
                =performance.totals[:backdrop]
  .col-md-3

app/views/users/index.haml
.text-center
  %h2.mb-5 Select your Scorecard
.px-5.row.justify-content-md-center.pb-4
  -User.all.each do |user|
    .col-md-4.mb-3
      .card.p-3.scorecard
        %p=link_to user.name, scorecard_user_path(user)

app/views/users/scorecard.haml
.px-5.pb-3.pt-2
  .text-center
    %h1.mb-5="#{@user.name}, be nice... or don't"
  =form_for :scorecard, url: scorecard_user_path(@user) do |f|
    -@user.scores_excluding_me.all.each do |score|
      .row.mb-4.pt-2
        .col-6
          %h3.mb-0
            =link_to score.performance.title, score.performance.link, target: "_blank"
          %p=score.performance.user.name
        .col-2.text-center.pt-1
          =f.number_field "#{score.id}[song]", value: (score.song || 0), max: 10, min: 0
          %span.label Performance
        .col-2.text-center.pt-1
          =f.number_field "#{score.id}][outfit]", value: (score.outfit || 0), max: 10, min: 0
          %span.label Outfit
        .col-2.text-center.pt-1
          =f.number_field "#{score.id}[backdrop]", value: (score.backdrop || 0), max: 10, min: 0
          %span.label Stage
    .text-center.pt-4
      =f.submit